name: Copy  Docker Image
description: ' Docker Image across the same repo as a different image'

inputs:
    repo:
      type: string
      required: true
    image:
      type: string
      required: true
    image-as:
      type: string
      required: true 
    tag:
      type: string
      required: true
    with-tag:
      type: string
      required: true
    registry:
      type: string
      required: false
      default: ghcr.io
    username:
      type: string
      required: true
    token:
        type: string
        required: true


runs:
    using: "composite"
    steps:

     - uses: actions/setup-go@v2
       with:
        go-version: 1.15

     - uses: imjasonh/setup-crane@v0.1

     - name: tag image
       shell: bash
       run: |
         echo "${{ inputs.token }}" | crane auth login ${{ inputs.registry }} --username ${{ inputs.username }} --password-stdin
         crane  cp ${{ inputs.registry }}/${{ inputs.repo }}/${{ inputs.image }}:${{ inputs.tag }}  ${{ inputs.registry }}/${{ inputs.repo}}/${{ inputs.image-as }}:${{ inputs.with-tag }}

 
