name: Delete branch folder

on:
  delete:
    branches:
      - '*'
      - '!dx@scale'
jobs:
  remove:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo dx@scale branch and s3 remove folder
        id: Checkout
        uses: actions/checkout@v3
        with:
         args: --recursive
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        PATH_TO_DELETE: ${{ github.event.ref }}